#!/usr/bin/env sh
/usr/local/bin/limelight -m config width            3
/usr/local/bin/limelight -m config radius           0
/usr/local/bin/limelight -m config placement        inset # interior | exterior
/usr/local/bin/limelight -m config active_color     0xffbd93f9 #default 0xffbd93f9
/usr/local/bin/limelight -m config normal_color     0x00bd93f9 #default 0xff555555

echo "limelight configuration loaded.."
