---
# Tasks to complete before running roles
- hosts: localhost
  tags: always
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

# Run roles
- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation
