---
# Tasks to complete before running roles
- hosts: localhost
  tags: always
  connection: local
  pre_tasks:
    - name: Pre-run | Update package cache (Arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
      become: true

# Run roles
- hosts: workstation
  tags: workstation
  roles:
    - workstation
