#+TITLE: Dotfiles

These dotfiles are tailored for my preferences running Omarchy.
Multiple aspects of these configs build on top on the omarchy defaults, hence these will not work well on any other distro without major changes.

** Contents

This repository contains:
- Package installation scripts, managed through =omarchy-packages/=
- Configuration files for =nix=, =hypr=, and other applications
- Personal shell scripts in =bin/=
- A unified =dotfiles= management script for syncing configs and installing packages

** Getting Started

1. Clone this repository to =~/git/dotfiles=:
  #+begin_src bash
  git clone https://github.com/ThonyPrice/dotfiles.git ~/git/dotfiles
  #+end_src

2. Install packages:
  #+begin_src bash
  cd ~/git/dotfiles
  ./bin/dotfiles packages install
  #+end_src

3. Sync your configurations:
  #+begin_src bash
  ./bin/dotfiles config sync
  #+end_src

** Usage

Add dotfiles script to bin:
#+begin_src bash
./bin/stow-bin
#+end_src

Now the =dotfiles= script is executable from anywhere, use it to add install packages to this repository or new configs. This purpose of the script is to make it *simple keeping dotfiles up to date with system configurations*.

Run =dotfiles --help= to see all available commands.
