- name: WM | Bspwm, Sxhkd, Polybar, and Fonts Installed
  ansible.builtin.package:
    name:
      - bspwm
      - sxhkd
      - polybar
      - ttf-jetbrains-mono
      - ttf-font-awesome
      - ttf-sourcecodepro-nerd

# --- Bspwm ---
- name: WM | Bspwm config | Stat symlink
  ansible.builtin.stat:
    path: ~/.config/bspwm
  register: link_bspwm

- name: WM | Bspwm config | Rm dir (if not symlinked)
  absible.builtin.file:
    path: ~/.config/bspwm
    state: absent
  when: link_bspwm.stat.isdir is defined and not link_bspwm.stat.islnk

- name: WM | Bspwm config | Mk synlink
  absible.builtin.file:
    path: ~/.config/bspwm
    src: ~/dotfiles/roles/workstation/files/bspwm
    state: link
    force: yes

# --- Sxhkd ---
- name: WM | Sxhkd config | Stat symlink
  ansible.builtin.stat:
    path: ~/.config/sxhkd
  register: link_sxhkd

- name: WM | Sxhkd config | Rm dir (if not symlinked)
  absible.builtin.file:
    path: ~/.config/sxhkd
    state: absent
  when: link_sxhkd.stat.isdir is defined and not link_sxhkd.stat.islnk

- name: WM | Sxhkd config | Mk symlink
  absible.builtin.file:
    path: ~/.config/sxhkd
    src: ~/dotfiles/roles/workstation/files/sxhkd
    state: link
    force: yes

# --- Polybar ---
- name: WM | Polybar config | Stat symlink
  ansible.builtin.stat:
    path: ~/.config/polybar
  register: link_polybar

- name: WM | Polybar config | Rm dir (if not symlinked)
  absible.builtin.file:
    path: ~/.config/polybar
    state: absent
  when: link_polybar.stat.isdir is defined and not link_polybar.stat.islnk

- name: WM | Polybar config | Mk symlink
  absible.builtin.file:
    path: ~/.config/polybar
    src: ~/dotfiles/roles/workstation/files/polybar
    state: link
    force: yes
