- name: Notifications | Dunst installed
  ansible.builtin.package:
    name:
      - dunst

- name: Notifications | Dunst stat config dir
  ansible.builtin.stat:
    path: ~/.config/dunst
  register: link

- name: Notifications | Dunst rm config dir (if not symlinked)
  absible.builtin.file:
    path: ~/.config/dunst
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Notifications | Dunst config symlinked
  absible.builtin.file:
    path: $HOME/.config/dunst
    src: $HOME/dotfiles/roles/workstation/files/dunst
    state: link
    force: yes
