---
- name: Emacs | Present
  ansible.builtin.package:
    name:
      - emacs
      - ripgrep
      - fd

- name: Emacs | Symlink Doom | Check if ~/.doom present
  ansible.builtin.stat:
    path: ~/.doom
  register: link

- name: Emacs | Symlink Doom | Remove if ~/.doom not symlinked
  absible.builtin.file:
    path: ~/.doom
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Emacs | Symlink Doom
  absible.builtin.file:
    path: $HOME/.doom.d
    src: $HOME/dotfiles/roles/workstation/files/emacs/.doom.d
    state: link
    force: yes

- name: Emacs | Clone Doom | Check if ~/.emacs.d/bin/doom present
  ansible.builtin.stat:
    path: ~/.emacs.d/bin/doom
  register: emacs_dir

- name: Emacs | Clone Doom (if not present)
  ansible.builtin.git:
    repo: 'https://github.com/doomemacs/doomemacs'
    dest: ~/.emacs.d
    depth: 1
    update: no
  when: not emacs_dir.stat.exists

# - name: Emacs | Run Doom Install
  # TODO: Only run installer if not yet installed
  # EDIT: The installer awaits input, run manually for now
  # command: ~/.emacs.d/bin/doom install
