- name: Emacs | Present
  package:
    name: 
      - emacs
      - ripgrep
      - fd

- name: Emacs | Symlink Doom | Check if ~/.doom present
  stat:
    path: ~/.doom
  register: link

- name: Emacs | Symlink Doom | Remove if ~/.doom not symlinked
  file:
    path: ~/.doom
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Emacs | Symlink Doom
  file: path=$HOME/.doom.d
        src=$HOME/dotfiles/roles/workstation/files/emacs/.doom.d
        state=link
        force=yes

- name: Emacs | Clone ~/.emacs.d | Check if ~/.emacs.d present
  stat:
    path: ~/.emacs.d
  register: emacs_dir

- name: Emacs | Clone ~/.emacs.d (if not present)
  git:
    repo: 'https://github.com/hlissner/doom-emacs.git'
    dest: ~/.emacs.d
    update: no
  when: not emacs_dir.stat.exists

# - name: Emacs | Run Doom Install
  # TODO: Only run installer if not yet installed
  # EDIT: The installer awaits input, run manually for now
  # command: ~/.emacs.d/bin/doom install
