- name: install firefox
  package:
    name:
      - firefox

- name: Check for betterfox profile
  ansible.builtin.find:
    paths: /home/thony/.mozilla/firefox
    patterns: '.*betterfox'
    use_regex: true
    file_type: directory
  register: betterfox_profile

- name: Create betterfox profile
  shell: |
    firefox --createprofile betterfox
  when: betterfox_profile.matched == 0
  become: false

- name: Get betterfox profile directory
  find:
    paths: /home/thony/.mozilla/firefox
    patterns: '.*betterfox'
    use_regex: true
    file_type: directory
  register: betterfox_profile_dir

- name: Symlink betterfox configs
  file: path="{{ betterfox_profile.files.0.path }}/{{ item }}"
        src="/home/thony/dotfiles/roles/workstation/files/firefox/{{ item }}"
        state=link
        force=yes
  loop:
    - user.js
    - chrome
  become: false
