- name: Browser | Firefox installed
  ansible.builtin.package:
    name:
      - firefox

- name: Browser | Firefox profile | Betterfox stat profile
  ansible.builtin.find:
    paths: ~/.mozilla/firefox
    patterns: '.*betterfox'
    use_regex: true
    file_type: directory
  register: betterfox_profile

- name: Browser | Firefox profile | Betterfox create profile (if not present)
  shell: |
    firefox --createprofile betterfox
  when: betterfox_profile.matched == 0

- name: Browser | Firefox profile | Betterfox get profile path
  find:
    paths: ~/.mozilla/firefox
    patterns: '.*betterfox'
    use_regex: true
    file_type: directory
  register: betterfox_profile_dir

- name: Browser | Firefox profile | Betterfox symlink profile configs
  absible.builtin.file:
    path: "{{ betterfox_profile.files.0.path }}/{{ item }}"
    src: "~/dotfiles/roles/workstation/files/firefox/{{ item }}"
    state: link
    force: yes
  loop:
    - user.js
    - chrome
