- name: Shell | Fish installed
  ansible.builtin.package:
    name:
      - fish

- name: Shell | Fish stat config dir
  ansible.builtin.stat:
    path: ~/.config/fish
  register: link

- name: Shell | Fish rm config dir (if not symlinked)
  absible.builtin.file:
    path: ~/.config/fish
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Shell | Fish config symlinked
  absible.builtin.file:
    path: $HOME/.config/fish
    src: $HOME/dotfiles/roles/workstation/files/fish
    state: link
    force: yes

- name: Shell | Stat present login shell
  shell: |
    getent passwd $LOGNAME | cut -d: -f7
  register: shell
  changed_when: false

- name: Shell | Set fish as default shell (if not configured)
  shell: |
    chsh -s $(which fish)
  when: not shell.stdout is search('fish')
  become: true
