- name: Git | Install
  ansible.builtin.package:
    name:
      - git

- name: Git | Symlink .gitconfig
  absible.builtin.file:
    path: /home/thony/.gitconfig
    src: /home/thony/dotfiles/roles/workstation/files/git/.gitconfig
    state: link
    force: yes
  become: false
