- name: install packages
  package:
    name:
      - acpilight 
      - gtop
      - fish
      - kitty  
      - neovim
      - npm
      - python-pip
      - ranger
      - rofi
      - slack-desktop
      - spotify
      - stow
      - ttf-jetbrains-mono

- name: Vim | Setup backup dir
  shell: mkdir -p /home/thony/.local/share/nvim/backup

- name: Vim | Setup pynvim
  shell: python3 -m pip install --user --upgrade pynvim
