- name: install packages
  package:
    name:
      - stow
      # - acpilight 
      - gtop
      # - fish
      # - kitty  
      - neovim
      # - npm
      # - python-pip
      # - ranger
      # - rofi
      # - slack-desktop
      # - spotify
      # - stow
      # - ttf-jetbrains-mono

- name: Symlink neovim dotfiles
  shell: stow -d /home/thony/Git/dotfiles/.config/{{item}}/ -t /home/thony/.config/{{item}}/
  with_items:
    - nvim
