- name: install packages
  package:
    name:
      # - acpilight 
      - gtop
      # - fish
      # - kitty  
      # - neovim
      # - npm
      # - python-pip
      # - ranger
      # - rofi
      # - slack-desktop
      # - spotify
      # - stow
      # - ttf-jetbrains-mono
