# --- Tasks to be migrated for "Base" role ---
- name: Git
  tags: git
  ansible.builtin.import_tasks: git.yml

- name: Keybindings
  tags: keybindings
  ansible.builtin.import_tasks: keybindings.yml
  when: ansible_distribution == "Archlinux"

- name: Periphials
  tags: periphials
  ansible.builtin.import_tasks: periphials.yml
  when: ansible_distribution == "Archlinux"
  become: true

- name: Terminal
  tags: terminal,kitty
  ansible.builtin.import_tasks: kitty.yml

- name: Nvim
  tags: nvim,vim
  ansible.builtin.import_tasks: nvim.yml

- name: Fish
  tags: shell,fish
  ansible.builtin.import_tasks: fish.yml

# --- Tasks in Workstation role ---
- name: Emacs
  tags: emacs
  ansible.builtin.import_tasks: emacs.yml

- name: Firefox
  tags: firefox
  ansible.builtin.import_tasks: firefox.yml

- name: Software
  tags: software
  ansible.builtin.import_tasks: software.yml

- name: Spotify
  tags: spotify
  ansible.builtin.import_tasks: spotify.yml


- name: Setup wm
  tags: wm,bspwm,sxhkd,polybar
  ansible.builtin.import_tasks: arch-wm.yml
  when: ansible_distribution == "Archlinux"

- name: Notifications
  tags: notifications,duinst
  ansible.builtin.import_tasks: dunst.yml
  when: ansible_distribution == "Archlinux"

- name: Wallpapers
  tags: wallpapers
  ansible.builtin.import_tasks: wallpaper.yml
