# --- Tasks to be migrated for "Base" role ---
- name: git
  tags: git
  import_tasks: git.yml

- name: Keybindings
  tags: keybindings
  import_tasks: keybindings.yml
  when: ansible_distribution == "Archlinux"

- name: Periphials
  tags: periphials
  import_tasks: periphials.yml
  when: ansible_distribution == "Archlinux"
  become: true

- name: Terminal
  tags: terminal,kitty
  import_tasks: kitty.yml

- name: install nvim
  tags: nvim,vim
  import_tasks: nvim.yml

- name: install fish
  tags: shell,fish
  import_tasks: fish.yml

# --- Tasks in Workstation role ---
- name: emacs
  tags: emacs
  import_tasks: emacs.yml

- name: firefox
  tags: firefox
  import_tasks: firefox.yml

- name: software
  tags: software
  import_tasks: software.yml

- name: spotify
  tags: spotify
  import_tasks: spotify.yml


- name: setup wm
  tags: wm,bspwm,sxhkd,polybar
  import_tasks: arch-wm.yml
  when: ansible_distribution == "Archlinux"

- name: notifications
  tags: notifications,duinst
  import_tasks: dunst.yml
  when: ansible_distribution == "Archlinux"

- name: sync wallpapers
  tags: wallpapers
  import_tasks: wallpaper.yml

# - name: install pkgs
  # package:
    # name:
      # - acpilight 
      # - gtop
      # - fish
      # - kitty  
      # - neovim
      # - npm
      # - python-pip
      # - ranger
      # - rofi
      # - slack-desktop
      # - spotify
      # - stow
      # - ttf-jetbrains-mono
