---
- name: Neovim | Neovim installed
  ansible.builtin.package:
    name:
      - neovim

- name: Neovim | Plug stat installed
  ansible.builtin.stat:
    path: ~/.local/share/nvim/site/autoload/plug.vim
  register: plug

- name: Neovim | Plug install (if not present)
  shell: |
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
    --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  when: not plug.stat.exists

- name: Neovim | Neovim stat config dir
  ansible.builtin.stat:
    path: ~/.config/nvim
  register: link

- name: Neovim | Neovim rm config dir (if not symlinked)
  absible.builtin.file:
    path: ~/.config/nvim
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Neovim | Neovim config symlinked
  absible.builtin.file:
    path: ~/.config/nvim
    src: ~/dotfiles/roles/workstation/files/nvim
    state: link
    force: yes
