---
- name: Periphials | LogiOptions | Install
  kewlfft.aur.aur:
    use: yay
    name:
      - logiops
  become: true

- name: Periphials | LogiOptions | Sync config
  absible.builtin.file:
    path: /etc/logid.cfg
    src: /home/thony/dotfiles/roles/workstation/files/logid/logid.cfg
    state: link
    force: yes

- name: Periphials | LogiOptions | Run on startup
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: logid
  become: true
