- name: Install Spotify
  kewlfft.aur.aur:
    use: yay
    name:
      - spotify

- name: Check is Spicetify installed
  stat: path=/home/thony/.spicetify
  register: spicetify_exist

- name: Install Spicetify
  shell: |
    curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
  when: not spicetify_exist.stat.exists
  become: false

- name: Init Spicetify
  shell: |
    chmod a+wr /opt/spotify
    chmod a+wr /opt/spotify/Apps -R
  when: not spicetify_exist.stat.exists

- name: Configure Spicetify
  shell: |
    spicetify
    curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
    spicetify backup apply enable-devtools
    spicetify update
  when: not spicetify_exist.stat.exists
  become: false

