---
- name: Spotify | Install (Arch)
  kewlfft.aur.aur:
    use: yay
    name:
      - spotify
  when: ansible_distribution == "Archlinux"

- name: Spotify | Install (MacOS)
  ansible.builtin.shell: |
    echo "TODO: Install Spotify for MacOS"
  when: ansible_distribution == 'MacOSX'

- name: Spotify | Spicetify | Installed stat
  ansible.builtin.stat:
    path: /home/thony/.spicetify
  register: spicetify_exist

- name: Spotify | Spicetify | Install (if not present)
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL \
    https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh \
    | sh
  when: not spicetify_exist.stat.exists
  become: false

- name: Spotify | Spicetify | Setup chmod (Arch)
  ansible.builtin.shell: |
    chmod a+wr /opt/spotify
    chmod a+wr /opt/spotify/Apps -R
  when: not spicetify_exist.stat.exists and ansible_distribution == "Archlinux"

- name: Spotify | Spicetify | Configure marketplace
  ansible.builtin.shell: |
    spicetify
    # Install marketplace to configure themes inside the Spotify client
    set -o pipefail
    curl -fsSL \
    https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh \
    | sh
    spicetify backup apply enable-devtools
    spicetify update
  when: not spicetify_exist.stat.exists
  become: false
