- name: Wallpapers | Nitrogen present
  ansible.builtin.package:
    name:
      - nitrogen

- name: Wallpapers | Stat ~/wallpapers dir
  ansible.builtin.stat:
    path: ~/wallpapers
  register: link

- name: Wallpapers | Remove ~/wallpapers dir (if not symlinked)
  absible.builtin.file:
    path: ~/wallpaper
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Wallpapers | Symlink ~/wallpapers
  absible.builtin.file:
    path: ~/wallpapers
    src: ~/dotfiles/wallpapers
    state: link
    force: yes
