- name: Wallpapers | Nitrogen present
  package:
    name:
      - nitrogen

- name: Wallpapers | Stat ~/wallpapers dir
  stat:
    path: ~/wallpapers
  register: link

- name: Wallpapers | Remove ~/wallpapers dir (if not symlinked)
  file:
    path: ~/wallpaper
    state: absent
  when: link.stat.isdir is defined and not link.stat.islnk

- name: Wallpapers | Symlink ~/wallpapers
  file: path=~/wallpapers
        src=~/dotfiles/wallpapers
        state=link
        force=yes
