#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "JetBrains Mono:Bold:12.0"
spacebar -m config icon_font            "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color     0xff282a36
spacebar -m config foreground_color     0xfff8f8f2
spacebar -m config space_icon_color     0xffbd93f9
spacebar -m config power_icon_color     0xfff1fa8c
spacebar -m config battery_icon_color   0xffff79c6
spacebar -m config dnd_icon_color       0xfff8f8f2
spacebar -m config clock_icon_color     0xfff8f8f2
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip	          VI VII IVIII IX X
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%d/%m/%y %R"
spacebar -m config right_shell          on
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "yabai -m query --spaces --space | jq -r '.type'"

echo "spacebar configuration loaded.."
