#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
picom -b &
# Network Applet
killall -q firewall-applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Keyboard
setxkbmap -option caps:escape
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# BSPWM config
bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          32
bspc config bottom_padding       0.5%
bspc config left_padding         0.5%
bspc config right_padding        0.5%
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM Dracula coloring
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

# Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8

# Fullscreen applications
bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen

# Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Xfce4-terminal state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

#open applications on specific workspaces
bspc rule -a Spotify desktop='^1' follow=on
bspc rule -a Slack desktop='^2' follow=on
bspc rule -a Firefox desktop='^5' follow=off

